name: Build and deploy React app to Azure

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Upload build folder
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: react-build

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: User-App-frontend
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
